>>> add_integer(1,2)
3
>>> add_integer(2,1) 
3
>>> add_integer(5,1) 
6
>>> add_integer(5,56) 
61
>>> add_integer(-2,7) 
5
>>> add_integer(2,-7) 
-5
>>> add_integer(1.4,2) 
3
>>> add_integer(2,1.4) 
3
>>> add_integer(2)     
100
>>> add_integer(-17) 
81
>>> add_integer(1,"4") 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Thomas\Documents\Holberton\holbertonschool-higher_level_programming\python-test_driven_development\0-add_integer.py", line 15, in add_integer
    raise TypeError("b must be an integer")
TypeError: b must be an integer
>>> add_integer("4",1) 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Thomas\Documents\Holberton\holbertonschool-higher_level_programming\python-test_driven_development\0-add_integer.py", line 13, in add_integer
    raise TypeError("a must be an integer")
TypeError: a must be an integer
>>> add_integer("4","1") 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Thomas\Documents\Holberton\holbertonschool-higher_level_programming\python-test_driven_development\0-add_integer.py", line 13, in add_integer
    raise TypeError("a must be an integer")
TypeError: a must be an integer
>>> add_integer()       
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: add_integer() missing 1 required positional argument: 'a'
>>> add_integer(1,3,4) 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: add_integer() takes from 1 to 2 positional arguments but 3 were given